### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by jitterxx** [jitterxx/rework#18]
http://127.0.0.1:8080/cases/add?uuid=61779b3a-475a-11e5-8833-f46d04d35cbd

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "rework_webapp.py", line 963, in add
    obj = rwObjects.Case()
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/sergey/test/rework/prototype 1/modules/prototype1_objects_and_orm_mappings.py", line 949, in __init__
    self.read()
  File "/home/sergey/test/rework/prototype 1/modules/prototype1_objects_and_orm_mappings.py", line 968, in read
    cats = get_ktree_for_object(session)
  File "/home/sergey/test/rework/prototype 1/modules/prototype1_objects_and_orm_mappings.py", line 1704, in get_ktree_for_object
    raise ("Ошибка доступа к базе References. Ошибка :  %s" % str(e))
TypeError: exceptions must be old-style classes or derived from BaseException, not str

**Comment by jitterxx** [comment]
Исправлен raise.
